### ISSUE TITLE
Cory's issues todo

### ISSUE THREAD

**Issue by coryshields** [githubschool/apple-pie#17]
- [x] Create a branch
- [x] Edit the file
- [x] Commit the changes
- [x] Create a Pull Request
- [x] Request a review
- [x] Make a change based on the review
- [x] Get approval
- [ ] Merge the Pull Request
